# BMAD Core - GitHub Edition Configuration
# Version: 1.1.0

name: bmad-core-github
version: 1.1.0
short-title: Core + GitHub Pack
description: >-
  Complete BMAD Method implementation using GitHub Issues, Milestones, and
  native GitHub workflows. No external dependencies required.
author: BMAD Community
slashPrefix: BMadGH

# GitHub Integration
github:
  # Task management via GitHub Issues
  tasks:
    use_milestones_for_epics: true
    use_labels_for_status: true

    status_flow:
      - backlog # Not yet scheduled for current sprint
      - todo # Ready to start, all dependencies met
      - doing # Currently in development
      - review # In PR review / QA testing
      - done # Completed, merged, closed

    # Label conventions (auto-created by setup-labels.sh)
    labels:
      status:
        - status:backlog
        - status:todo
        - status:doing
        - status:review
        - status:done
      types:
        - type:epic
        - type:story
        - type:task
        - type:bug
      priority:
        - priority:p0
        - priority:p1
        - priority:p2
        - priority:p3
      size:
        - size:xs
        - size:s
        - size:m
        - size:l
        - size:xl

    # Automation
    auto_link_pr_to_issue: true
    auto_close_on_merge: true
    enforce_single_status_label: true
    validate_dependencies: true

  # Projects v2
  projects:
    use_projects_v2: true
    default_view: "board"
    auto_move_on_label_change: true

  # Pull requests
  pull_requests:
    branch_prefix: "feature/"
    require_issue_reference: true
    auto_update_issue_status: true

# Documents (markdown in git)
documents:
  use_files: true
  docs_path: "docs/"

  structure:
    prd: "docs/prd/"
    architecture: "docs/architecture/"
    specs: "docs/specs/"
    guides: "docs/guides/"
    notes: "docs/notes/"

  use_frontmatter: true
  auto_commit: false # Let agents commit explicitly

# QA Configuration
qa:
  automated_review:
    enabled: true

    # When to trigger
    trigger_on:
      - pr_opened
      - pr_updated
      - manual_dispatch

    # Auto-approve and merge? (Recommended: false for safety)
    auto_merge_on_pass: false

    # Require human review for major failures?
    require_human_on_major_fail: true

    # Model configuration
    model: "claude-sonnet-4-20250514"
    temperature: 0.3 # Lower = more consistent verdicts

    # Thresholds
    thresholds:
      min_test_coverage: 80 # Percent
      max_code_smells: 5
      max_complexity: 15

# Dev Team Lead Configuration
dev_team_lead:
  # Default execution mode (v3.2.0+)
  default_mode: "in-context" # or "parallel"

  # Parallel execution settings
  parallel:
    max_developers: 5
    max_qa_reviewers: 3
    wave_batch_size: 10 # Max tasks per wave

# Agent Settings
agents:
  github_first: true # Use GitHub as primary system

  # Agent personas
  available:
    - analyst
    - pm
    - architect
    - dev
    - qa
    - sm
    - po
    - dev-team-lead
    - ux-expert

# Workflows
workflows:
  greenfield:
    - planning
    - development
  brownfield:
    - planning
    - development

# Knowledge Base (Optional)
knowledge_base:
  use_github_search: true
  pattern_library_enabled: true

  # Optional: Connect to Archon for semantic search
  archon:
    enabled: false # User enables if they want
    url: null # Set if using Archon

# Git Settings
git:
  commit_prefix: "docs" # Prefix for documentation commits
  auto_push: false # Agents ask before pushing

# Integration
integrations:
  slack:
    enabled: false
    webhook_url: null

  jira:
    enabled: false
    sync_issues: false

# Metrics & Analytics
metrics:
  track_velocity: true
  track_cycle_time: true
  track_burndown: true
  export_format: "json" # or "csv"
